# Generated by Django 3.1.4 on 2021-01-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='parent_tweet_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
