# Generated by Django 3.1.4 on 2021-01-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210110_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='image_path',
            field=models.ImageField(default='images', upload_to='static/images/'),
        ),
    ]
