# Generated by Django 3.1.4 on 2021-04-17 23:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210115_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='image_path',
        ),
        migrations.AddField(
            model_name='tweet',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='images/'),
        ),
    ]
