# Generated by Django 3.1.4 on 2021-04-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20210417_2013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.AddField(
            model_name='tweet',
            name='image_path',
            field=models.ImageField(blank=True, upload_to='tweet_images/'),
        ),
    ]
